Make the package
giuliocalzolari/salesforce-timecard pull request #15
Opened 2020-09-18 08:55 UTC by 1oglop1

Fixes #13 
Implements a simple test #14 

### Required change in travis

@giuliocalzolari Could you please generate a PYPI Token of from the project and add it to the travis env as `PYPI_TOKEN`

2020-09-18 16:46 UTC, 1oglop1 commented
@giuliocalzolari Tests are passing now, I've noticed the problem with usage of `datetime.date.today()` so I monkey patched  the fixed date for the test.

2020-09-21 15:09 UTC, giuliocalzolari requested changes

2020-09-21 15:09 UTC, giuliocalzo commented on salesforce_timecard/core.py
> +            self.sf.pse__Timecard_Header__c.delete_cmd(_id)
@1oglop1 I believe this is a typo... 

```
self.sf.pse__Timecard_Header__c.delete(_id)
```

2020-09-22 05:46 UTC, 1oglop1 commented on salesforce_timecard/core.py
> +            self.sf.pse__Timecard_Header__c.delete_cmd(_id)
I've added suffix `_cmd` to `list`, `delete`, and `add` due to the `list` was shadowing built-in `list()`.

2020-10-14 13:08 UTC, merged

2020-10-14 13:15 UTC, giuliocalzolari commented
@1oglop1 it seems the tests are failing https://travis-ci.org/github/giuliocalzolari/salesforce-timecard